FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c adaptive_avg_pool2d
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c add
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c avg_pool2d
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c batch_norm
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c binary_cross_entropy_with_logits
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c bmm
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c cat
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c conv2d
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c cross_entropy
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c dropout
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c dropout2d
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c einsum
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c ger
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c grid_sample
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c group_norm
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c histc
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c index_select
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c layer_norm
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c index_select
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c linear
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c masked_fill
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c masked_fill_
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c max
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c max_pool2d
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c meshgrid
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c meshgrid3d
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c mse_loss
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c mul_
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c mv
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c nonzero
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c norm
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c normalize
FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c pad
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c permute
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c rand
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c randperm
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c relu
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c reshape
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c softmax
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c sort
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c squeeze
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c stack
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c topk
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c transpose
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c unbind
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c unique
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c unsqueeze
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c view
# FRAMEWORK=torch python3 ./long_tail_bench/api/api.py -st 1 -c where